language: python
sudo: required
dist: xenial
python: '3.7'
env:
  global:
  - CODECOV_TOKEN="f29bb0af-060f-47fd-a582-82b09c72deca"
install:
- pip install -r requirements.txt codecov
script:
- python -m pytest -v --cov-config .coveragerc --cov=./ tests
after_success:
- codecov
notifications:
  on_success: change
  on_failure: always
deploy:
  - provider: pypi
    username: matt.bachmann
    password:
      secure: bUJe4K9vr7xm9mEBsb+xwJ8i7h0dFynLJ0Ze603n0CloPy5961II1PfRDmbh+w/VdP2cfuUXrxf0AjZjJw5rD0/aDjNP9r7Xajf7L9gFvjmls4OMnWRUBhequRb+6nAnb0Q8+ErDyfP5ztYRR8T9JB9U77hOISo+LRoky3VE8gpMzUzMYfl/1diN9NLUTh7tQL0gUksRqWy6SHqOeRCYx19zEn9WU7mIXadXqyPRwB8pTiELNYYx8hpHFKzRzlpKa/Yf93mHwNqgAX25hpDUA3mpzWT21HLZc1w64UZhgXePSElz98clEBsw6D7PsWdSEiA0+q6J2z+Stg5n6FOLkL3Kc09Vp/73+4Qeuo3A+m+a3/8xOxiWYFaw10yRmaKvdX43VUQyA9crMzAKl4Ev9F4HcReNo7Oz70ekrJUe4SK6o9v3D/sU+tNUih4xBNN0J6ivAipZt1mp3SWHg4devEUOrHP0oGNuZakqq0I+vdwK1zptCuwh6e4AlVSNalE62Y4KKLTtxcvUqdSvCQuPng4GScOm25M1yNBedce/HQLfv4zWWaUzd56YElw++tMPtSc3aLEn9j8Z8DfNoDzFhiKAeVhaO/b8AHIHvpGwQt+IvX7HSgX/waVXtcs2EXVa9Ib/brTeok9Zer7XBocJp4IS83XeV3A6JA6/Ek5plS4=
    on:
      tags: true
